FROM node:20.17.0-alpine

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

COPY . /app
RUN npx prisma generate && npm run build

CMD npm run migration:run && npm run start:prod
