FROM node:20.17.0-alpine AS builder

RUN apk add --no-cache bash curl

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

COPY . /app
RUN npx prisma generate && npm run build


FROM node:20.17.0-alpine

WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./
COPY --from=builder /app/.env.staging ./

COPY entrypoint.railway-dev.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

CMD ["/app/entrypoint.sh"]
