FROM node:20.17.0-alpine

RUN apk add --no-cache bash curl
RUN curl -sfS https://dotenvx.sh/install.sh | sh
RUN npm i -g @nestjs/cli typescript ts-node
COPY . /usr/src/app

WORKDIR /usr/src/app
RUN npm install

# RUN if [ ! -f .env ]; then cp env-example-relational .env; fi
RUN npm run build

CMD ["dotenvx", "run", "--", "npm", "run", "start:prod"]