services:
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    environment:
      - DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}
    ports:
      - ${MAIL_CLIENT_PORT}:1080
    expose:
      - 1080
      - 1025

  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}
    healthcheck:
      test:
        ['CMD', 'curl', '-f', 'http://localhost:${APP_PORT}/api/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    env_file:
      - .env.production
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
      - redis-data:/data
    entrypoint: ["/usr/local/bin/redis-entrypoint.sh"]
    restart: unless-stopped

volumes:
  redis-data:
