FROM node:20.17.0-alpine

RUN apk add --no-cache bash curl
RUN curl -sfS https://dotenvx.sh/install.sh | sh

WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json .
COPY prisma .
RUN npm ci

COPY . /usr/src/app
RUN npm run build

CMD ["dotenvx", "run", "--", "npm", "run", "start:prod"]