FROM node:20.17.0-alpine

WORKDIR /usr/src/app
COPY package.json .
COPY package-lock.json .
RUN npm ci --ignore-scripts

COPY . /usr/src/app
RUN npx prisma generate
RUN npm run build && find dist -type f

CMD ["sh", "-c", "npm run start:prod"]
# CMD ["sh", "-c", "npx prisma migrate deploy && npm run start:prod"]
