import { StoryReview } from './domain/story-review';
import { StoryReviewOverview } from './domain/story-review-overview';
import { StoryReviewHistogram } from './domain/story-review-histogram';
import { userData } from '../users/users.data';

export const storyReviewsData: StoryReview[] = [
  {
    id: 1,
    title: 'Story 1',
    comment: 'Excellent plot development and character arcs',
    rating: 4,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    user: userData[0],
  },
  {
    id: 2,
    title: 'Story 2',
    comment: 'Very engaging narrative with strong themes',
    rating: 4,
    createdAt: new Date('2024-01-16'),
    updatedAt: new Date('2024-01-16'),
    user: userData[0],
  },
  {
    id: 3,
    title: 'Story 3',
    comment: 'Well-crafted dialogue and pacing',
    rating: 4,
    createdAt: new Date('2024-01-17'),
    updatedAt: new Date('2024-01-17'),
    user: userData[0],
  },
  {
    id: 4,
    title: 'Story 4',
    comment: 'Compelling world-building and atmosphere',
    rating: 4,
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-18'),
    user: userData[0],
  },
  {
    id: 5,
    title: 'Story 5',
    comment: 'Great character development throughout',
    rating: 4,
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-19'),
    user: userData[0],
  },
  {
    id: 6,
    title: 'Story 6',
    comment: 'Interesting plot twists and revelations',
    rating: 4,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    user: userData[0],
  },
  {
    id: 7,
    title: 'Story 7',
    comment: 'Strong emotional impact and resonance',
    rating: 4,
    createdAt: new Date('2024-01-21'),
    updatedAt: new Date('2024-01-21'),
    user: userData[0],
  },
  {
    id: 8,
    title: 'Story 8',
    comment: 'Masterful use of literary techniques',
    rating: 4,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    user: userData[0],
  },
  {
    id: 9,
    title: 'Story 9',
    comment: 'Vivid descriptions and imagery',
    rating: 4,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
    user: userData[0],
  },
  {
    id: 10,
    title: 'Story 10',
    comment: 'Excellent pacing and story structure',
    rating: 4,
    createdAt: new Date('2024-01-24'),
    updatedAt: new Date('2024-01-24'),
    user: userData[0],
  },
  {
    id: 11,
    title: 'Story 11',
    comment: 'Memorable characters and interactions',
    rating: 4,
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    user: userData[0],
  },
  {
    id: 12,
    title: 'Story 12',
    comment: 'Thought-provoking themes and messages',
    rating: 4,
    createdAt: new Date('2024-01-26'),
    updatedAt: new Date('2024-01-26'),
    user: userData[0],
  },
  {
    id: 13,
    title: 'Story 13',
    comment: 'Skillful handling of complex themes',
    rating: 4,
    createdAt: new Date('2024-01-27'),
    updatedAt: new Date('2024-01-27'),
    user: userData[0],
  },
  {
    id: 14,
    title: 'Story 14',
    comment: 'Engaging from start to finish',
    rating: 4,
    createdAt: new Date('2024-01-28'),
    updatedAt: new Date('2024-01-28'),
    user: userData[0],
  },
  {
    id: 15,
    title: 'Story 15',
    comment: 'Well-balanced plot and character development',
    rating: 4,
    createdAt: new Date('2024-01-29'),
    updatedAt: new Date('2024-01-29'),
    user: userData[0],
  },
  {
    id: 16,
    title: 'Story 16',
    comment: 'Creative and original storytelling',
    rating: 4,
    createdAt: new Date('2024-01-30'),
    updatedAt: new Date('2024-01-30'),
    user: userData[0],
  },
  {
    id: 17,
    title: 'Story 17',
    comment: 'Excellent use of symbolism',
    rating: 4,
    createdAt: new Date('2024-01-31'),
    updatedAt: new Date('2024-01-31'),
    user: userData[0],
  },
  {
    id: 18,
    title: 'Story 18',
    comment: 'Strong narrative voice throughout',
    rating: 4,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    user: userData[0],
  },
  {
    id: 19,
    title: 'Story 19',
    comment: 'Well-executed story arc',
    rating: 4,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
    user: userData[0],
  },
  {
    id: 20,
    title: 'Story 20',
    comment: 'Impressive character relationships',
    rating: 4,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
    user: userData[0],
  },
  {
    id: 21,
    title: 'Story 21',
    comment: 'Compelling narrative structure',
    rating: 4,
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
    user: userData[0],
  },
  {
    id: 22,
    title: 'Story 22',
    comment: 'Rich and detailed world-building',
    rating: 4,
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
    user: userData[0],
  },
  {
    id: 23,
    title: 'Story 23',
    comment: 'Excellent character motivations',
    rating: 4,
    createdAt: new Date('2024-02-06'),
    updatedAt: new Date('2024-02-06'),
    user: userData[0],
  },
  {
    id: 24,
    title: 'Story 24',
    comment: 'Well-crafted emotional moments',
    rating: 4,
    createdAt: new Date('2024-02-07'),
    updatedAt: new Date('2024-02-07'),
    user: userData[0],
  },
  {
    id: 25,
    title: 'Story 25',
    comment: 'Satisfying conclusion and resolution',
    rating: 4,
    createdAt: new Date('2024-02-08'),
    updatedAt: new Date('2024-02-08'),
    user: userData[0],
  },
];

export const storyReviewHistogramData: StoryReviewHistogram[] = [
  {
    rating: 5,
    numberOfReviews: 0,
  },
  {
    rating: 4,
    numberOfReviews: 25,
  },
  {
    rating: 3,
    numberOfReviews: 0,
  },
  {
    rating: 2,
    numberOfReviews: 0,
  },
  {
    rating: 1,
    numberOfReviews: 0,
  },
];

export const storyReviewOverviewData: StoryReviewOverview = {
    rating: 4,
    numberOfReviews: 25,
    histogram: storyReviewHistogramData,
    outStanding: storyReviewsData[0],
  };