- name: Install dependencies
  run: npm ci

- name: Generate Prisma Client
  run: npx prisma generate

- name: Build project
  run: npm run build

- name: Start App
  run: npm run start:prod
